---
- name: This playbook is to create user
  hosts: all
  become: true
  vars_files: 
    - user.yaml  
  tasks: 
   - name: creating user {{ user }}
     # user: name=jhon1
     user:
       name: "{{ user }}"

